# Especifica que se va a usar una 
# imagen de PHP e instala las extensiones necesarias (mysqli, pdo, pdo_mysql).


FROM mcr.microsoft.com/devcontainers/php:1-8.2-bullseye

RUN docker-php-ext-install mysqli pdo pdo_mysql